name: loanguides
description: A new Flutter application.

publish_to: 'none'


version: 3.0.0+3


environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  images_picker:
  cloud_firestore:
  firebase_core:
  share:
  auto_animated:
  font_awesome_flutter:
  url_launcher:
  expandable:
  firebase_storage:
  facebook_audience_network:


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora/Lora-VariableFont_wght.ttf
  
  
  
  
  
  
  
  
  
  
  
  
  
  
